In [1]:

!pip install numpy


In [14]:
import numpy as np

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

arr1.reshape(1,5)
# 1 row 5 cols
print(arr1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[1 2 3 4 5]


In [15]:
arr=np.arange(0,10,2).reshape(5,1)

print(arr)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
arr1=np.array([10,20,30,40,50])
arr2=np.array([50,60,70,80,90])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 60  80 100 120 140]
[-40 -40 -40 -40 -40]
[ 500 1200 2100 3200 4500]
[0.2        0.33333333 0.42857143 0.5        0.55555556]


In [25]:
arr1=np.arange(0,10)
print(arr1)
print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.sin(arr1))
print(np.log(arr1))

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\Sandeep\AppData\Local\Temp\ipykernel_27556\1585768180.py:6: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr1))


In [26]:
# slicing and indexing

arr1=np.array([[1,2,3,4],[5,6,7,8],[7,8,9,10]])
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 7  8  9 10]]


In [29]:
arr1[0][0]
arr1[1:,2:]

array([[ 7,  8],
       [ 9, 10]])

In [30]:
arr1[0][0]=100
print(arr1)

[[100   2   3   4]
 [  5   6   7   8]
 [  7   8   9  10]]


In [32]:
arr1[1:]=100
print(arr1)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [33]:
data=np.arange(1,20)
mean=np.mean(data)
std=np.std(data)

normalization=(data-mean)/std

print(normalization)

[-1.64316767 -1.46059349 -1.2780193  -1.09544512 -0.91287093 -0.73029674
 -0.54772256 -0.36514837 -0.18257419  0.          0.18257419  0.36514837
  0.54772256  0.73029674  0.91287093  1.09544512  1.2780193   1.46059349
  1.64316767]
